dist: trusty
sudo: false
language: node_js
addons:
  chrome: stable
node_js:
  - "10"
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:5000 &
install:
  npm ci
script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build
  - npm run e2e
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  on:
    branch: master
  target-branch: gh-pages
  local-dir: build
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
